import json
import codecs

with open('data.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

data['ar'] = {
    'nav_home': 'الرئيسية',
    'nav_about': 'من أنا',
    'nav_skills': 'المهارات',
    'nav_projects': 'أعمال مميزة',
    'nav_experience': 'رحلتي',
    'nav_contact': 'لنتباحث',
    'hero_greeting': 'مرحباً بك 👋، أنا',
    'hero_name': 'مصطفى',
    'hero_lastname': 'إبراهيم',
    'hero_subtitle_1': 'مطور ويب متكامل.',
    'hero_subtitle_2': 'سحر الواجهة الأمامية.',
    'hero_subtitle_3': 'واجهات برمجة قابلة للتطوير.',
    'hero_subtitle_4': 'تطبيقات الويب.',
    'hero_specialize': 'متخصص في ',
    'hero_desc': 'مطور شغوف مقيم في المنصورة، مصر. أحول الأفكار إلى تطبيقات ويب قوية باستخدام لارافيل وأحدث تقنيات الويب.',
    'hero_btn': 'تواصل معي',
    'hero_scroll': 'مرر لأسفل',
    'about_title': 'من أنا',
    'about_age_label': '25 عاماً',
    'about_exp_label': '+1 سنة خبرة',
    'about_lead': 'خريج كلية الحاسبات والمعلومات، جامعة المنصورة، تخصص علوم الحاسب (CS).',
    'about_p': 'أنا متعلم سريع، ودائماً حريص على إتقان تقنيات جديدة. بعيداً عن البرمجة، أنا شغوف بالمساهمة في المشاريع مفتوحة المصدر ومساعدة مجتمع المطورين. هدفي هو بناء تطبيقات ويب تحدث فرقاً حقيقياً.',
    'about_location_lbl': 'الموقع',
    'about_location_val': 'المنصورة، مصر',
    'about_email_lbl': 'البريد',
    'about_email_val': 'sasa9121963@gmail.com',
    'about_freelance_lbl': 'العمل الحر',
    'about_freelance_val': 'متاح',
    'about_download_btn': 'تحميل السيرة الذاتية',
    'skills_title': 'ترسانتي',
    'skills_backend': 'هندسة الواجهة الخلفية',
    'skills_frontend': 'هندسة الواجهة الأمامية',
    'skills_tools': 'أدوات العمل',
    'skill_laravel_title': 'Laravel / PHP',
    'skill_laravel_desc': 'Blade، واجهات RESTful، كود نظيف وقابل للصيانة.',
    'skill_mysql_title': 'MySQL',
    'skill_mysql_desc': 'قواعد بيانات علائقية، استعلامات معقدة، وعلاقات.',
    'skill_security_title': 'الأمان',
    'skill_security_desc': 'JWT، الجلسات، التوثيق والتفويض.',
    'skill_js_title': 'JavaScript',
    'skill_js_desc': 'AJAX، طلبات غير متزامنة، واجهة مستخدم ديناميكية.',
    'skill_tailwind_title': 'Tailwind & CSS',
    'skill_tailwind_desc': 'تصميم متجاوب، لمسات حديثة، Bootstrap.',
    'skill_html_title': 'HTML5',
    'skill_html_desc': 'هيكلة دلالية، وتحسين محركات البحث.',
    'projects_title': 'أعمال مميزة',
    'proj1_title': 'منصة تجارة إلكترونية',
    'proj1_desc': 'لارافيل، MySQL، Vue.js',
    'proj2_title': 'لوحة تحكم لحظية',
    'proj2_desc': 'PHP، WebSockets، Tailwind',
    'proj3_title': 'واجهة برمجة تطبيقات مصغرة',
    'proj3_desc': 'لارافيل، JWT، Postman',
    'exp_title': 'رحلتي',
    'exp_1_date': 'أبريل 2025 - أبريل 2027',
    'exp_1_title': 'ضابط احتياط (الخدمة العسكرية)',
    'exp_1_tech': 'القوات المسلحة المصرية',
    'exp_1_desc': 'أخدم حالياً كضابط احتياط. أطور مهارات القيادة والانضباط وحل المشكلات الاستراتيجية في بيئات العمل عالية الضغط.',
    'exp_2_date': 'أغسطس 2024 - أبريل 2025',
    'exp_2_title': 'مطور ويب متكامل',
    'exp_2_tech': 'Laravel • HTML • CSS • JS',
    'exp_2_desc': 'عملت فوراً بعد التخرج في بناء تطبيقات خلفية قوية وواجهات مستخدم متجاوبة. تركت العمل لأداء الخدمة العسكرية.',
    'exp_3_date': 'مستمر',
    'exp_3_title': 'متعلم مدى الحياة',
    'exp_3_tech': 'المصادر المفتوحة والتقنيات الحديثة',
    'exp_3_desc': 'أتعلم تقنيات جديدة باستمرار وأواكب اتجاهات الصناعة، سعياً دائماً لتحسين الكفاءة وتوسيع نطاق مهاراتي.',
    'contact_title': 'لنتباحث.',
    'contact_desc': 'هل لديك مشروع في ذهنك أو تريد فقط إلقاء التحية؟ أنا منفتح دائماً لمناقشة تطوير الويب، الفرص الجديدة، والمشاريع المثيرة.',
    'contact_name_lbl': 'اسمك',
    'contact_email_lbl': 'بريدك الإلكتروني',
    'contact_msg_lbl': 'رسالتك',
    'contact_send_btn': 'إرسال الرسالة',
    'contact_sending': 'جاري الإرسال...',
    'contact_sent': 'تم الإرسال!',
    'contact_error': 'خطأ في الإرسال',
    'footer_text': 'بُني بشغف بواسطة مصطفى إبراهيم.'
}

with open('data.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=4, ensure_ascii=False)
